version: '3'

services:
  snippet-api-container:
    container_name: "snippet-api-container"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      DB_USER: sa
      DB_PASSWORD: password
      DB_NAME: compose-db
      DB_HOST: snippet_api_db
      DB_PORT: 5432

  snippet_api_db:
    container_name: snippet_api_db
    image: postgres:12
    ports:
      - "5434:5434"
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: password
      POSTGRES_DB: compose-db